/**:
  ros__parameters:
    min_x: -0.5
    max_x: 1.0
    min_y: -1.0
    max_y: 1.0
    min_z: 0.0
    max_z: 6.0
    voxel_size_x: 0.2
    voxel_size_y: 0.2
    voxel_size_z: 0.2
    D_voxel_size_x: 0.02
    D_voxel_size_y: 0.02
    D_voxel_size_z: 0.02
