/**:
  ros__parameters:
    min_x: 0.0
    max_x: 4.0
    min_y: -0.5
    max_y: 1.0
    min_z: -0.9
    max_z: 1.0
    voxel_size_x: 0.2
    voxel_size_y: 0.2
    voxel_size_z: 0.2
    D_voxel_size_x: 0.0015
    D_voxel_size_y: 0.01
    D_voxel_size_z: 0.01
    voxel_search_range: 2
    ball_radius: 0.1